# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gems_window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QFrame, QGridLayout,
    QHeaderView, QLabel, QLayout, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QSpacerItem, QSplitter, QTabWidget,
    QTableView, QToolBar, QToolButton, QWidget)

from gemsedit.gui.CustomClickableLabel import ClickableLabel
from gemsedit.gui import gemsedit_rc

class Ui_ViewsWindow(object):
    def setupUi(self, ViewsWindow):
        if not ViewsWindow.objectName():
            ViewsWindow.setObjectName(u"ViewsWindow")
        ViewsWindow.resize(1400, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ViewsWindow.sizePolicy().hasHeightForWidth())
        ViewsWindow.setSizePolicy(sizePolicy)
        ViewsWindow.setMinimumSize(QSize(0, 0))
        ViewsWindow.setMaximumSize(QSize(16777215, 16777215))
        font = QFont()
        font.setFamilies([u"Verdana"])
        font.setPointSize(12)
        ViewsWindow.setFont(font)
        ViewsWindow.setTabShape(QTabWidget.Rounded)
        self.actionOpen = QAction(ViewsWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon = QIcon()
        icon.addFile(u":/newPrefix/media/1409888970_Folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionNew = QAction(ViewsWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon1 = QIcon()
        icon1.addFile(u":/newPrefix/media/add-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionClose = QAction(ViewsWindow)
        self.actionClose.setObjectName(u"actionClose")
        icon2 = QIcon()
        icon2.addFile(u":/newPrefix/media/1409889639_Cancel.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClose.setIcon(icon2)
        self.actionQuit = QAction(ViewsWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon3 = QIcon()
        icon3.addFile(u":/newPrefix/media/1409888938_Log Out.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionTask_Configuration = QAction(ViewsWindow)
        self.actionTask_Configuration.setObjectName(u"actionTask_Configuration")
        icon4 = QIcon()
        icon4.addFile(u":/newPrefix/media/1409888901_Settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTask_Configuration.setIcon(icon4)
        self.actionTask_Actions = QAction(ViewsWindow)
        self.actionTask_Actions.setObjectName(u"actionTask_Actions")
        icon5 = QIcon()
        icon5.addFile(u":/newPrefix/media/1409889836_Properties.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTask_Actions.setIcon(icon5)
        self.actionDocumentation = QAction(ViewsWindow)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        icon6 = QIcon()
        icon6.addFile(u":/newPrefix/media/1409889623_Help.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDocumentation.setIcon(icon6)
        self.actionRun_Environment = QAction(ViewsWindow)
        self.actionRun_Environment.setObjectName(u"actionRun_Environment")
        icon7 = QIcon()
        icon7.addFile(u":/newPrefix/media/1409971621_Play.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRun_Environment.setIcon(icon7)
        self.actionMedia = QAction(ViewsWindow)
        self.actionMedia.setObjectName(u"actionMedia")
        icon8 = QIcon()
        icon8.addFile(u":/newPrefix/media/folder-images-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMedia.setIcon(icon8)
        self.actionLocate_GEMSrun = QAction(ViewsWindow)
        self.actionLocate_GEMSrun.setObjectName(u"actionLocate_GEMSrun")
        self.actionSave = QAction(ViewsWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave.setEnabled(False)
        icon9 = QIcon()
        icon9.addFile(u":/newPrefix/media/Save-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon9)
        self.actionSaveEnv = QAction(ViewsWindow)
        self.actionSaveEnv.setObjectName(u"actionSaveEnv")
        self.actionSaveEnv.setEnabled(True)
        self.actionSaveEnv.setIcon(icon9)
        self.actionNetwork_Graph = QAction(ViewsWindow)
        self.actionNetwork_Graph.setObjectName(u"actionNetwork_Graph")
        icon10 = QIcon()
        icon10.addFile(u":/newPrefix/media/network_color.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNetwork_Graph.setIcon(icon10)
        self.centralwidget = QWidget(ViewsWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy1)
        self.tabWidget.setMinimumSize(QSize(1114, 679))
        self.tabWidget.setBaseSize(QSize(1114, 679))
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setDocumentMode(True)
        self.maintab = QWidget()
        self.maintab.setObjectName(u"maintab")
        self.gridLayout_10 = QGridLayout(self.maintab)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.splitter_2 = QSplitter(self.maintab)
        self.splitter_2.setObjectName(u"splitter_2")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy2)
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.splitter_2.setHandleWidth(7)
        self.layoutWidget = QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.gridLayout_3 = QGridLayout(self.layoutWidget)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")
        font1 = QFont()
        font1.setFamilies([u"Verdana"])
        font1.setPointSize(16)
        font1.setItalic(False)
        self.label_4.setFont(font1)
        self.label_4.setStyleSheet(u"background-color: rgb(102, 204, 255)")
        self.label_4.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)

        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMaximumSize(QSize(50, 50))
        self.label_6.setPixmap(QPixmap(u":/newPrefix/media/Antialiasfactory-Jewelry-Agate.ico"))
        self.label_6.setScaledContents(True)

        self.gridLayout_3.addWidget(self.label_6, 0, 3, 1, 2)

        self.viewDel_toolButton = QToolButton(self.layoutWidget)
        self.viewDel_toolButton.setObjectName(u"viewDel_toolButton")
        icon11 = QIcon()
        icon11.addFile(u":/newPrefix/media/delete-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.viewDel_toolButton.setIcon(icon11)

        self.gridLayout_3.addWidget(self.viewDel_toolButton, 1, 4, 1, 1)

        self.viewAdd_toolButton = QToolButton(self.layoutWidget)
        self.viewAdd_toolButton.setObjectName(u"viewAdd_toolButton")
        self.viewAdd_toolButton.setIcon(icon1)

        self.gridLayout_3.addWidget(self.viewAdd_toolButton, 1, 3, 1, 1)

        self.labelAppName = QLabel(self.layoutWidget)
        self.labelAppName.setObjectName(u"labelAppName")
        font2 = QFont()
        font2.setFamilies([u"Verdana"])
        font2.setPointSize(24)
        font2.setBold(True)
        self.labelAppName.setFont(font2)

        self.gridLayout_3.addWidget(self.labelAppName, 0, 0, 1, 2)

        self.view_tableView = QTableView(self.layoutWidget)
        self.view_tableView.setObjectName(u"view_tableView")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.view_tableView.sizePolicy().hasHeightForWidth())
        self.view_tableView.setSizePolicy(sizePolicy3)
        self.view_tableView.setMaximumSize(QSize(16777215, 16777215))
        self.view_tableView.setBaseSize(QSize(276, 532))
        font3 = QFont()
        font3.setFamilies([u"Verdana"])
        font3.setPointSize(14)
        font3.setBold(True)
        self.view_tableView.setFont(font3)
        self.view_tableView.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.view_tableView.setDragEnabled(True)
        self.view_tableView.setDragDropMode(QAbstractItemView.InternalMove)
        self.view_tableView.setAlternatingRowColors(True)
        self.view_tableView.setSelectionMode(QAbstractItemView.SingleSelection)
        self.view_tableView.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.view_tableView.horizontalHeader().setVisible(False)
        self.view_tableView.horizontalHeader().setStretchLastSection(True)
        self.view_tableView.verticalHeader().setVisible(False)

        self.gridLayout_3.addWidget(self.view_tableView, 2, 0, 1, 5)

        self.horizontalSpacer_6 = QSpacerItem(90, 28, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_3.addItem(self.horizontalSpacer_6, 1, 1, 1, 2)

        self.horizontalSpacer = QSpacerItem(18, 20, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_3.addItem(self.horizontalSpacer, 0, 2, 1, 1)

        self.splitter_2.addWidget(self.layoutWidget)
        self.splitter = QSplitter(self.splitter_2)
        self.splitter.setObjectName(u"splitter")
        sizePolicy2.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy2)
        self.splitter.setOrientation(Qt.Vertical)
        self.splitter.setHandleWidth(7)
        self.layoutWidget1 = QWidget(self.splitter)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.gridLayout_5 = QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.label = QLabel(self.layoutWidget1)
        self.label.setObjectName(u"label")
        font4 = QFont()
        font4.setFamilies([u"Verdana"])
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setItalic(False)
        self.label.setFont(font4)

        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.dbfilename_Label = QLabel(self.layoutWidget1)
        self.dbfilename_Label.setObjectName(u"dbfilename_Label")
        self.dbfilename_Label.setFont(font)

        self.gridLayout.addWidget(self.dbfilename_Label, 0, 1, 1, 1)

        self.horizontalSpacer_2 = QSpacerItem(268, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer_2, 0, 2, 1, 1)

        self.objectsButton = QPushButton(self.layoutWidget1)
        self.objectsButton.setObjectName(u"objectsButton")
        self.objectsButton.setFont(font1)

        self.gridLayout.addWidget(self.objectsButton, 0, 3, 1, 1)


        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.label_3 = QLabel(self.layoutWidget1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font1)
        self.label_3.setStyleSheet(u"background-color: rgb(102, 204, 255)")
        self.label_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)

        self.horizontalSpacer_4 = QSpacerItem(538, 28, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_4.addItem(self.horizontalSpacer_4, 0, 1, 1, 1)

        self.actionAdd_toolButton = QToolButton(self.layoutWidget1)
        self.actionAdd_toolButton.setObjectName(u"actionAdd_toolButton")
        self.actionAdd_toolButton.setIcon(icon1)

        self.gridLayout_4.addWidget(self.actionAdd_toolButton, 0, 2, 1, 1)

        self.actionDel_toolButton = QToolButton(self.layoutWidget1)
        self.actionDel_toolButton.setObjectName(u"actionDel_toolButton")
        self.actionDel_toolButton.setIcon(icon11)

        self.gridLayout_4.addWidget(self.actionDel_toolButton, 0, 3, 1, 1)

        self.VAL_tableView = QTableView(self.layoutWidget1)
        self.VAL_tableView.setObjectName(u"VAL_tableView")
        self.VAL_tableView.setMinimumSize(QSize(622, 192))
        self.VAL_tableView.setFont(font)
        self.VAL_tableView.setEditTriggers(QAbstractItemView.DoubleClicked)
        self.VAL_tableView.setDragEnabled(True)
        self.VAL_tableView.setDragDropMode(QAbstractItemView.InternalMove)
        self.VAL_tableView.setAlternatingRowColors(True)
        self.VAL_tableView.setSelectionMode(QAbstractItemView.SingleSelection)
        self.VAL_tableView.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.VAL_tableView.horizontalHeader().setStretchLastSection(True)
        self.VAL_tableView.verticalHeader().setVisible(False)

        self.gridLayout_4.addWidget(self.VAL_tableView, 1, 0, 1, 4)


        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)

        self.splitter.addWidget(self.layoutWidget1)
        self.layoutWidget2 = QWidget(self.splitter)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.gridLayout_9 = QGridLayout(self.layoutWidget2)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6 = QGridLayout()
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.label_7 = QLabel(self.layoutWidget2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMaximumSize(QSize(16777215, 28))
        font5 = QFont()
        font5.setFamilies([u"Verdana"])
        font5.setPointSize(14)
        font5.setBold(False)
        font5.setItalic(False)
        self.label_7.setFont(font5)
        self.label_7.setStyleSheet(u"background-color: rgb(102, 204, 255)")
        self.label_7.setAlignment(Qt.AlignCenter)

        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)

        self.fgOpen_toolButton = QToolButton(self.layoutWidget2)
        self.fgOpen_toolButton.setObjectName(u"fgOpen_toolButton")
        icon12 = QIcon()
        icon12.addFile(u":/newPrefix/media/folder-open-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.fgOpen_toolButton.setIcon(icon12)

        self.gridLayout_6.addWidget(self.fgOpen_toolButton, 0, 1, 1, 1)

        self.fgCopy_toolButton = QToolButton(self.layoutWidget2)
        self.fgCopy_toolButton.setObjectName(u"fgCopy_toolButton")
        icon13 = QIcon()
        icon13.addFile(u":/newPrefix/media/1409970886_circle-arrow-left-48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.fgCopy_toolButton.setIcon(icon13)

        self.gridLayout_6.addWidget(self.fgCopy_toolButton, 0, 2, 1, 1)

        self.fgDel_toolButton = QToolButton(self.layoutWidget2)
        self.fgDel_toolButton.setObjectName(u"fgDel_toolButton")
        self.fgDel_toolButton.setIcon(icon11)

        self.gridLayout_6.addWidget(self.fgDel_toolButton, 0, 3, 1, 1)

        self.fgPic_plainTextEdit = QPlainTextEdit(self.layoutWidget2)
        self.fgPic_plainTextEdit.setObjectName(u"fgPic_plainTextEdit")
        self.fgPic_plainTextEdit.setMinimumSize(QSize(285, 0))
        self.fgPic_plainTextEdit.setMaximumSize(QSize(16777215, 60))
        self.fgPic_plainTextEdit.setFont(font)
        self.fgPic_plainTextEdit.setReadOnly(True)

        self.gridLayout_6.addWidget(self.fgPic_plainTextEdit, 1, 0, 1, 4)

        self.fgPic_label = ClickableLabel(self.layoutWidget2)
        self.fgPic_label.setObjectName(u"fgPic_label")
        self.fgPic_label.setMinimumSize(QSize(259, 239))
        self.fgPic_label.setMaximumSize(QSize(16777215, 16777215))
        self.fgPic_label.setFont(font)
        self.fgPic_label.setFrameShape(QFrame.Box)

        self.gridLayout_6.addWidget(self.fgPic_label, 2, 0, 1, 4)


        self.gridLayout_9.addLayout(self.gridLayout_6, 0, 0, 1, 1)

        self.gridLayout_7 = QGridLayout()
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.label_8 = QLabel(self.layoutWidget2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setMaximumSize(QSize(16777215, 28))
        self.label_8.setFont(font5)
        self.label_8.setStyleSheet(u"background-color: rgb(102, 204, 255)")
        self.label_8.setAlignment(Qt.AlignCenter)

        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)

        self.bgOpen_toolButton = QToolButton(self.layoutWidget2)
        self.bgOpen_toolButton.setObjectName(u"bgOpen_toolButton")
        self.bgOpen_toolButton.setIcon(icon12)

        self.gridLayout_7.addWidget(self.bgOpen_toolButton, 0, 1, 1, 1)

        self.bgCopy_toolButton = QToolButton(self.layoutWidget2)
        self.bgCopy_toolButton.setObjectName(u"bgCopy_toolButton")
        icon14 = QIcon()
        icon14.addFile(u":/newPrefix/media/1409970876_circle-arrow-right-48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.bgCopy_toolButton.setIcon(icon14)

        self.gridLayout_7.addWidget(self.bgCopy_toolButton, 0, 2, 1, 1)

        self.bgDel_toolButton = QToolButton(self.layoutWidget2)
        self.bgDel_toolButton.setObjectName(u"bgDel_toolButton")
        self.bgDel_toolButton.setIcon(icon11)

        self.gridLayout_7.addWidget(self.bgDel_toolButton, 0, 3, 1, 1)

        self.bgPic_plainTextEdit = QPlainTextEdit(self.layoutWidget2)
        self.bgPic_plainTextEdit.setObjectName(u"bgPic_plainTextEdit")
        self.bgPic_plainTextEdit.setMinimumSize(QSize(285, 0))
        self.bgPic_plainTextEdit.setMaximumSize(QSize(16777215, 60))
        self.bgPic_plainTextEdit.setFont(font)
        self.bgPic_plainTextEdit.setReadOnly(True)

        self.gridLayout_7.addWidget(self.bgPic_plainTextEdit, 1, 0, 1, 4)

        self.bgPic_label = ClickableLabel(self.layoutWidget2)
        self.bgPic_label.setObjectName(u"bgPic_label")
        self.bgPic_label.setMinimumSize(QSize(259, 239))
        self.bgPic_label.setMaximumSize(QSize(16777215, 16777215))
        self.bgPic_label.setFont(font)
        self.bgPic_label.setFrameShape(QFrame.Box)

        self.gridLayout_7.addWidget(self.bgPic_label, 2, 0, 1, 4)


        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 1, 1, 1)

        self.gridLayout_8 = QGridLayout()
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.label_13 = QLabel(self.layoutWidget2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setMaximumSize(QSize(16777215, 28))
        self.label_13.setFont(font5)
        self.label_13.setStyleSheet(u"background-color: rgb(102, 204, 255)")
        self.label_13.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.label_13, 0, 0, 1, 1)

        self.olOpen_toolButton = QToolButton(self.layoutWidget2)
        self.olOpen_toolButton.setObjectName(u"olOpen_toolButton")
        self.olOpen_toolButton.setIcon(icon12)

        self.gridLayout_8.addWidget(self.olOpen_toolButton, 0, 1, 1, 1)

        self.olDel_toolButton = QToolButton(self.layoutWidget2)
        self.olDel_toolButton.setObjectName(u"olDel_toolButton")
        self.olDel_toolButton.setIcon(icon11)

        self.gridLayout_8.addWidget(self.olDel_toolButton, 0, 2, 1, 1)

        self.olPic_plainTextEdit = QPlainTextEdit(self.layoutWidget2)
        self.olPic_plainTextEdit.setObjectName(u"olPic_plainTextEdit")
        self.olPic_plainTextEdit.setMinimumSize(QSize(286, 0))
        self.olPic_plainTextEdit.setMaximumSize(QSize(16777215, 60))
        self.olPic_plainTextEdit.setFont(font)
        self.olPic_plainTextEdit.setReadOnly(True)

        self.gridLayout_8.addWidget(self.olPic_plainTextEdit, 1, 0, 1, 3)

        self.olPic_label = ClickableLabel(self.layoutWidget2)
        self.olPic_label.setObjectName(u"olPic_label")
        self.olPic_label.setMinimumSize(QSize(259, 239))
        self.olPic_label.setMaximumSize(QSize(16777215, 16777215))
        self.olPic_label.setFont(font)
        self.olPic_label.setFrameShape(QFrame.Box)

        self.gridLayout_8.addWidget(self.olPic_label, 2, 0, 1, 3)


        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 2, 1, 1)

        self.splitter.addWidget(self.layoutWidget2)
        self.splitter_2.addWidget(self.splitter)

        self.gridLayout_10.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.tabWidget.addTab(self.maintab, "")
        self.logtab = QWidget()
        self.logtab.setObjectName(u"logtab")
        self.gridLayout_11 = QGridLayout(self.logtab)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.log_plainTextEdit = QPlainTextEdit(self.logtab)
        self.log_plainTextEdit.setObjectName(u"log_plainTextEdit")
        self.log_plainTextEdit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.log_plainTextEdit.setReadOnly(True)
        self.log_plainTextEdit.setPlainText(u"")

        self.gridLayout_11.addWidget(self.log_plainTextEdit, 0, 0, 1, 1)

        self.tabWidget.addTab(self.logtab, "")

        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        ViewsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(ViewsWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1400, 25))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuRun = QMenu(self.menubar)
        self.menuRun.setObjectName(u"menuRun")
        self.menuOther = QMenu(self.menubar)
        self.menuOther.setObjectName(u"menuOther")
        ViewsWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(ViewsWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setEnabled(True)
        self.toolBar.setFont(font)
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        ViewsWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuOther.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMedia)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionTask_Configuration)
        self.menuSettings.addAction(self.actionTask_Actions)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuRun.addAction(self.actionRun_Environment)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionLocate_GEMSrun)
        self.menuOther.addAction(self.actionNetwork_Graph)
        self.menuOther.addSeparator()
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSaveEnv)
        self.toolBar.addAction(self.actionClose)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMedia)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun_Environment)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTask_Configuration)
        self.toolBar.addAction(self.actionTask_Actions)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNetwork_Graph)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDocumentation)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()

        self.retranslateUi(ViewsWindow)
        self.actionQuit.triggered.connect(ViewsWindow.close)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(ViewsWindow)
    # setupUi

    def retranslateUi(self, ViewsWindow):
        ViewsWindow.setWindowTitle(QCoreApplication.translate("ViewsWindow", u"GEMS Editor - 2021 v1.0", None))
        self.actionOpen.setText(QCoreApplication.translate("ViewsWindow", u"Open", None))
        self.actionNew.setText(QCoreApplication.translate("ViewsWindow", u"New", None))
        self.actionClose.setText(QCoreApplication.translate("ViewsWindow", u"Close", None))
        self.actionQuit.setText(QCoreApplication.translate("ViewsWindow", u"Quit", None))
        self.actionTask_Configuration.setText(QCoreApplication.translate("ViewsWindow", u"Settings", None))
#if QT_CONFIG(tooltip)
        self.actionTask_Configuration.setToolTip(QCoreApplication.translate("ViewsWindow", u"Edit Global Environmnet Settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionTask_Actions.setText(QCoreApplication.translate("ViewsWindow", u"Actions", None))
#if QT_CONFIG(tooltip)
        self.actionTask_Actions.setToolTip(QCoreApplication.translate("ViewsWindow", u"Edit Global Environment Actions", None))
#endif // QT_CONFIG(tooltip)
        self.actionDocumentation.setText(QCoreApplication.translate("ViewsWindow", u"Help", None))
        self.actionRun_Environment.setText(QCoreApplication.translate("ViewsWindow", u"Run", None))
#if QT_CONFIG(tooltip)
        self.actionRun_Environment.setToolTip(QCoreApplication.translate("ViewsWindow", u"Run Current GEMS Environment", None))
#endif // QT_CONFIG(tooltip)
        self.actionMedia.setText(QCoreApplication.translate("ViewsWindow", u"Media Folder", None))
#if QT_CONFIG(tooltip)
        self.actionMedia.setToolTip(QCoreApplication.translate("ViewsWindow", u"Launch Media Folder Viewer", None))
#endif // QT_CONFIG(tooltip)
        self.actionLocate_GEMSrun.setText(QCoreApplication.translate("ViewsWindow", u"Locate GEMSrun", None))
        self.actionSave.setText(QCoreApplication.translate("ViewsWindow", u"Save", None))
        self.actionSaveEnv.setText(QCoreApplication.translate("ViewsWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSaveEnv.setToolTip(QCoreApplication.translate("ViewsWindow", u"Save Changes To Environment", None))
#endif // QT_CONFIG(tooltip)
        self.actionNetwork_Graph.setText(QCoreApplication.translate("ViewsWindow", u"Network Graph", None))
#if QT_CONFIG(tooltip)
        self.actionNetwork_Graph.setToolTip(QCoreApplication.translate("ViewsWindow", u"Launch Network Graph in Default Browser", None))
#endif // QT_CONFIG(tooltip)
        self.label_4.setText(QCoreApplication.translate("ViewsWindow", u"View List", None))
        self.label_6.setText("")
#if QT_CONFIG(tooltip)
        self.viewDel_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Deleted the selected view", None))
#endif // QT_CONFIG(tooltip)
        self.viewDel_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.viewAdd_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Add a new view", None))
#endif // QT_CONFIG(tooltip)
        self.viewAdd_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
        self.labelAppName.setText(QCoreApplication.translate("ViewsWindow", u"GEMS Editor", None))
        self.label.setText(QCoreApplication.translate("ViewsWindow", u"Currnet GEMS Environment: ", None))
        self.dbfilename_Label.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.objectsButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Manage objects for this view", None))
#endif // QT_CONFIG(tooltip)
        self.objectsButton.setText(QCoreApplication.translate("ViewsWindow", u"Ojbects", None))
        self.label_3.setText(QCoreApplication.translate("ViewsWindow", u"View Action List", None))
#if QT_CONFIG(tooltip)
        self.actionAdd_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Add new blank action for this view", None))
#endif // QT_CONFIG(tooltip)
        self.actionAdd_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.actionDel_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Delete currently selected view action", None))
#endif // QT_CONFIG(tooltip)
        self.actionDel_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
        self.label_7.setText(QCoreApplication.translate("ViewsWindow", u"Foreground Pic", None))
#if QT_CONFIG(tooltip)
        self.fgOpen_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Select foreground picture file", None))
#endif // QT_CONFIG(tooltip)
        self.fgOpen_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.fgCopy_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Copy background picture", None))
#endif // QT_CONFIG(tooltip)
        self.fgCopy_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.fgDel_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Clear foreground picture", None))
#endif // QT_CONFIG(tooltip)
        self.fgDel_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
        self.fgPic_label.setText("")
        self.label_8.setText(QCoreApplication.translate("ViewsWindow", u"Background Pic", None))
#if QT_CONFIG(tooltip)
        self.bgOpen_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Select background picture file", None))
#endif // QT_CONFIG(tooltip)
        self.bgOpen_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.bgCopy_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Copy foreground picture", None))
#endif // QT_CONFIG(tooltip)
        self.bgCopy_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.bgDel_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Clear background picture", None))
#endif // QT_CONFIG(tooltip)
        self.bgDel_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
        self.bgPic_label.setText("")
        self.label_13.setText(QCoreApplication.translate("ViewsWindow", u"Overlay Pic", None))
#if QT_CONFIG(tooltip)
        self.olOpen_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Select overlay picture file", None))
#endif // QT_CONFIG(tooltip)
        self.olOpen_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.olDel_toolButton.setToolTip(QCoreApplication.translate("ViewsWindow", u"Clear overlay picture", None))
#endif // QT_CONFIG(tooltip)
        self.olDel_toolButton.setText(QCoreApplication.translate("ViewsWindow", u"...", None))
        self.olPic_plainTextEdit.setPlainText("")
        self.olPic_label.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.maintab), QCoreApplication.translate("ViewsWindow", u"Main", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logtab), QCoreApplication.translate("ViewsWindow", u"Log", None))
        self.menuFile.setTitle(QCoreApplication.translate("ViewsWindow", u"File", None))
        self.menuSettings.setTitle(QCoreApplication.translate("ViewsWindow", u"Settings", None))
        self.menuHelp.setTitle(QCoreApplication.translate("ViewsWindow", u"Help", None))
        self.menuRun.setTitle(QCoreApplication.translate("ViewsWindow", u"Run", None))
        self.menuOther.setTitle(QCoreApplication.translate("ViewsWindow", u"Other", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("ViewsWindow", u"toolBar", None))
    # retranslateUi

