cursors = (
    "Crosshair",
    "Default",
    "Hand",
    "Help",
    "No",
    "Size",
    "Size_Down",
    "Size_Down_Left",
    "Size_Down_Right",
    "Size_Left",
    "Size_Left_Right",
    "Size_Right",
    "Size_Up",
    "Size_Up_Down",
    "Size_Up_Left",
    "Size_Up_Right",
    "Text",
    "Wait",
    "Wait_Arrow",
)

cursordict = {
    "Crosshair": "crosshair",
    "Default": None,
    "Hand": "hand",
    "Help": "help",
    "No": "no",
    "Size": "size",
    "Size_Down": "size_down",
    "Size_Down_Left": "size_down_left",
    "Size_Down_Right": "size_down_right",
    "Size_Left": "size_left",
    "Size_Left_Right": "size_left_right",
    "Size_Right": "size_right",
    "Size_Up": "size_up",
    "Size_Up_Down": "size_up_down",
    "Size_Up_Left": "size_up_left",
    "Size_Up_Right": "size_up_right",
    "Text": "text",
    "Wait": "wait",
    "Wait_Arrow": "wait_arrow",
}
